services:
  postgres:
    image: postgres:15-bookworm
    environment:
      POSTGRES_DATABASE: gcook
      POSTGRES_USER: gcook
      POSTGRES_PASSWORD: p4ssw0rd!
    volumes:
      - "./database/initdb.d:/docker-entrypoint-initdb.d:ro"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gcook"]
      start_period: 0s
      interval: 1s
      timeout: 5s
    ports:
      - "127.0.0.1:25432:5432"
      - "[::1]:25432:5432"

  app:
    profiles:
      - full
    build:
      target: builder
    tty: true
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: gcook
      DATABASE_PASSWORD: p4ssw0rd!
    depends_on:
      - postgres
    volumes:
      - .:/src
    ports:
      - "8080:8080"
